# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "push"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "jlmayorga/spring-boot-demo-chart"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  store:
    title: Storing Helm Chart
    type: helm
    stage: push
    arguments:
      action: push
      helm_version: 3.0.2
      chart_name: spring-boot-demo-chart
  
  

